name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: bajar_dependencia
      run: curl https://raw.githubusercontent.com/CurieBSP/sha256/master/sha256.c > ./sha256.c
    - name: compilar
      run: gcc ./sha5.c -o ./sha5
