name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: bajar_dependencia_h
      run: curl https://raw.githubusercontent.com/CurieBSP/sha256/master/sha256.h > ./sha256.h
    - name: bajar_dependencia_c
      run: curl https://raw.githubusercontent.com/CurieBSP/sha256/master/sha256.c > ./sha256.c
    - name: compilar
      run: gcc -static ./sha5.c -o ./sha5
    - uses: actions/upload-artifact@v3
      with:
        name: compilado
        path: ./sha5
